spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sampledb
    username: sampleuser
    password: samplepassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      names: DB_TO_CSV