services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-dev
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sampledb
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: samplepassword
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
networks:
  default:
    name: springboot3batchstarter_default