name: Build and Test with jOOQ and Docker

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Start MySQL with Docker Compose
        run: docker-compose up -d

      - name: Check Docker Compose Logs
        run: docker-compose logs mysql

      - name: Wait for MySQL to be ready
        run: |
          timeout 60s bash -c '
          until docker exec $(docker ps -qf "ancestor=mysql:latest") mysqladmin ping -uroot -prootpassword --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done
          '

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Wait for MySQL to be ready
        run: |
          until docker exec $(docker ps -qf "ancestor=mysql:latest") mysqladmin ping -uroot -prootpassword --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      - name: Generate jOOQ Classes and Build
        run: ./gradlew clean generateJooq build --info --stacktrace

      - name: Archive Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: build/reports/tests/test